import time

print(" ")
time.sleep(3)
print("       *          *************   *************")
time.sleep(0.2)
print("       *                *               *")
time.sleep(0.3)
print("       *                *               *")
time.sleep(0.5)
print(" * * * * * * *          *               *")
time.sleep(0.7)
print("       *                *               *")
time.sleep(0.7)
print("       *                *               *")
time.sleep(0.7)
print("       *                *               *")
time.sleep(0.9)
print(" ")
print("                *TTMoreSubs*                    ")
print(" ")
time.sleep(1)
print("Version ALPHA-0.1-udne-153 (Beta soon...) starting...")
time.sleep(5)
print(" ")
print("This is not real program, i've made it just for fun. MAY CRASH!!")
time.sleep(2)
print('')
nickname = input("Enter TikTok username >> ")

if nickname=="":
    print("Username cannot be empty.")
    time.sleep(5)
    print(" ")
    nickname = input("Enter CORRECT TikTok username >> ")

if nickname==" ":
    print("Username cannot be empty.")
    time.sleep(5)
    print(" ")
    nickname = input("Enter CORRECT TikTok username >> ")

time.sleep(1.2)
print(" ")
howmany = int(input("How many subs do you want to add? >> "))
time.sleep(2)
print(" ")
check = input("Are you sure? (Y/N) >> ")

if check=="N":
    time.sleep(0.5)
    print("Ok.")
    time.sleep(2)

if check=="n":
    time.sleep(0.5)
    print("Ok.")
    time.sleep(2)

if check=="Y":
    time.sleep(2)
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print("Connecting to tiktok.com...")
    time.sleep(3)
    print(" ")
    print("Adding", howmany, "more sub(s) to", nickname)
    time.sleep(1)
    print(" ")
    print("2% done...")
    time.sleep(0.2)
    print(" ")
    print("3% done...")
    time.sleep(0.4)
    print(" ")
    print("8% done...")
    time.sleep(1)
    print(" ")
    print("19% done...")
    time.sleep(2)
    print(" ")
    print("36% done...")
    time.sleep(2)
    print(" ")
    print(" ")
    print("Operation cancelled, reason: Connection dropped")
    time.sleep(2)
    print(" ")
    print(" ")
    print("Sorry, but we can't add", howmany, "more sub(s) to", nickname, "account.")
    time.sleep(1)
    print(" ")
    input("Press enter to confirm exit")
    print(" ")
    print("Bye!")
    time.sleep(5)

if check=="y":
    time.sleep(2)
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print("Connecting to tiktok.com...")
    time.sleep(3)
    print(" ")
    print("Adding", howmany, "more sub(s) to", nickname)
    time.sleep(1)
    print(" ")
    print("2% done...")
    time.sleep(0.2)
    print(" ")
    print("3% done...")
    time.sleep(0.4)
    print(" ")
    print("8% done...")
    time.sleep(1)
    print(" ")
    print("19% done...")
    time.sleep(2)
    print(" ")
    print("36% done...")
    time.sleep(2)
    print(" ")
    print(" ")
    print("Operation cancelled, reason: Connection dropped")
    time.sleep(2)
    print(" ")
    print(" ")
    print("Sorry, but we can't add", howmany, "more sub(s) to", nickname, "account.")
    time.sleep(1)
    print(" ")
    input("Press enter to confirm exit")
    print(" ")
    print("Bye!")
    time.sleep(5)